### ISSUE TITLE
Can't select text when dragging cursor

### ISSUE THREAD

**Issue by teaguestockwell** [ZhiyueYi/react-dancing-lines#1]
Hello,

This library is a very unique way to add the dancing line effect. Thanks for making it into a react component.

I was able to select text by double clicking, but I noticed that I can't use the cursor to select text by dragging when i'm rendering the dancing lines component. 

It looks like this is the behavior in the [demo](https://zhiyueyi.github.io/react-dancing-lines) as well. 

Is there something we can modify to fix the text select by dragging? 

Thanks

**Comment by zhiyue-yi** [comment]
Nice catch! It was caused by an unexpected `event.preventDefault()`, which I completely forget why I added that 1 year ago. lol

https://github.com/ZhiyueYi/react-dancing-lines/commit/64d64b13177c0ad7ab97dd059ce7fdebc1ed1ff8#diff-2abb0a9bb7d3cf97a819f02aee4ee1995e9679f4816d8bc421fb37e2c681f6adL156

And it's already fixed! Thanks
